//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieQuizApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Movy
    {
        [Key]
        public int MovieId { get; set; }
        //How to add foreign Key attribute
        [ForeignKey("Registration")]
        public int UserID { get; set; }
        public string Title { get; set; }
        public string genre { get; set; }
        public string primaryReleaseDate { get; set; }
        public string VoteAverage { get; set; }



        public virtual Registration Registration { get; set; }
    }
}
